#!/usr/bin/env bash

# Check if an argument is passed
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}" 
# Display usage message if no argument provided
    exit 1
fi

ping -c 5 "$1"  # Ping the specified IP address 5 times
