#!/usr/bin/env bash

# Check if an argument is passed


if [-z "$1"]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1

    # Display usage message if no argument provided

fi

ip_address = $1

# Ping the specified IP address 5 times

ping - c 5 "$ip_address"
